### ISSUE TITLE
Zene loop

### ISSUE THREAD

**Issue by hdani1337** [hdani1337/Pendroid-2019-2#6]
A zene loopolásánál mindig hagy egy kb. negyed másodpercnyi szünetet a játék, de a zene végén és elején nincs szünet.

**Comment by hdani1337** [comment]
.mp3, 22050Hz, 128kbps, mono -> laggol
.ogg, 44100Hz, 128kbps, mono -> laggol
.aac, 22050Hz, 128kbps, mono - > laggol
Ami szünetet lehetett, kivágtam a zenék elejéről és végéről, de nem segített sokat. 
Zeneszerkesztő-lejátszó programban rendesen megy a loop: https://www.youtube.com/watch?v=IhBtW1oa1g0

**Comment by zltmmikls10** [comment]
Szerkezd át 10hour mixbe oszt jólvan
